version: "3.7"

services:
  app:
    container_name: dstock
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - deps
      - app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/dstock
      - JWT_SECRET=dstockFkngScrt
      - REDIS_URL=redis://redis
      - ALPHAVANTAGE_API_KEY=0YKITDLKRIY84WUZ
      - TWELVEDATA_API_KEY=970a8c2e37044bfb82fe15f53f8ae7e7


networks:
  deps:
    external: true
  app:
    driver: bridge